kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: fanout
  namespace: fanout
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fanout
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        metricName: request_per_second
        averageValue: 100
        target:
          kind: Namespace
          name: fanout
        targetValue: 100